package utp.misiontic2022.c2.p47.reto4.vista;

import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import utp.misiontic2022.c2.p47.reto4.controlador.ControladorRequerimientos;
import utp.misiontic2022.c2.p47.reto4.modelo.vo.ConsolidadorLideresCiudadResidencia;
import utp.misiontic2022.c2.p47.reto4.modelo.vo.Lider;

/**
 *
 * @author hernan
 */
public class ConsultasGUI extends javax.swing.JFrame {
    public static final ControladorRequerimientos controlador = new ControladorRequerimientos();
    
    private javax.swing.JComboBox<String> ComboSelectorConsulta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel panelVistaConsulta;
    
    
    public ConsultasGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ComboSelectorConsulta = new javax.swing.JComboBox<>();
        panelVistaConsulta = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consultas proyectos");

        jLabel1.setBackground(new java.awt.Color(242, 244, 246));
        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(5, 88, 76));
        jLabel1.setText("Consultas  Proyecto Construcciones");

        jLabel2.setText("Selecciones Consulta");

        ComboSelectorConsulta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Segundo apellido <Ortiz>", "Transformacion Nombre", "Consolidado por ciudad saldos lideres" }));
        ComboSelectorConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboSelectorConsultaActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout panelVistaConsultaLayout = new javax.swing.GroupLayout(panelVistaConsulta);
        panelVistaConsulta.setLayout(panelVistaConsultaLayout);
        panelVistaConsultaLayout.setHorizontalGroup(
            panelVistaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVistaConsultaLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        panelVistaConsultaLayout.setVerticalGroup(
            panelVistaConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVistaConsultaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboSelectorConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelVistaConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboSelectorConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelVistaConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void ComboSelectorConsultaActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        int opcion = ComboSelectorConsulta.getSelectedIndex();
        switch(opcion){
            case 0: interfazConsultaOrtiz(); break;
            case 1: interfazConsultaTransformacionNombre(); break;
            case 2: interfazConsultaConsolidadosCiudad(); break;
        }
    }

    public void interfazConsultaOrtiz(){
        Object []titulos= {"Nombre", "Primer Apellido", "Segundo Apellido", "Salario"};
        try {
            ArrayList<Lider> resultado = controlador.consultarRequerimiento1();
            Object[][] datos=new Object[resultado.size()][4];
            int cont = 0;
            for (Lider lider:resultado){
                datos[cont][0] = lider.getNombre();
                datos[cont][1] = lider.getPrimerApellido();
                datos[cont][2] = lider.getSegundoApellido();
                datos[cont][3] = lider.getSalario();
                cont++;
            }
            jTable1.setModel(new DefaultTableModel(datos, titulos));
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, e.getMessage());

        }

        
        
        

    }
    
    public void interfazConsultaTransformacionNombre(){
      
        Object []titulos= {"Nombre"};
        try {
            ArrayList<Lider> resultado = controlador.consultarRequerimiento2();
            Object[][] datos=new Object[resultado.size()][1];
            int cont = 0;
            for (Lider lider:resultado){
                datos[cont][0] = lider.getNombre();
                cont++;
            }
            jTable1.setModel(new DefaultTableModel(datos, titulos));
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, e.getMessage());
    }
}
    public void interfazConsultaConsolidadosCiudad(){

        Object []titulos= {"Ciudad", "Salario Consolidado"};
        try {
            ArrayList<ConsolidadorLideresCiudadResidencia> listaConsolidado=
            controlador.consultarRequerimiento3();
            Object[][] datos=new Object[listaConsolidado.size()][2];
            int cont = 0;
            for(ConsolidadorLideresCiudadResidencia consolidadoCiudad: listaConsolidado)
         {
            datos[cont][0] = consolidadoCiudad.getCiudadResidencia();
            datos[cont][1] = consolidadoCiudad.getSalarios();
            cont++;
        }
            jTable1.setModel(new DefaultTableModel(datos, titulos));
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, e.getMessage());
    }

    }

}

